import 'package:bizi/constants/b_colors.dart';
import 'package:bizi/constants/b_icons.dart';
import 'package:bizi/constants/b_images.dart';
import 'package:bizi/constants/route_names.dart';
import 'package:bizi/constants/text_localizations.dart';
import 'package:bizi/redux/actions/user_actions.dart';
import 'package:bizi/redux/states/app_state.dart';
import 'package:bizi/utils/extensions.dart';
import 'package:bizi/utils/helpers.dart';
// import 'package:bizi/views/login/index.dart';
import 'package:bizi/views/widgets/bizi_app_wrapper.dart';
import 'package:bizi/views/widgets/bizi_text_field.dart';
import 'package:bizi/views/widgets/button.dart';
import 'package:bizi/views/widgets/custom_text.dart';
import 'package:bizi/views/widgets/language_select.dart';
import 'package:bizi/views/widgets/space.dart';
import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter_redux/flutter_redux.dart';
import 'package:get/get.dart';

import 'package:redux/redux.dart';
import 'package:sign_in_with_apple/sign_in_with_apple.dart';

part './screens/welcome.dart';
part './widgets/welcome_button.dart';
part './widgets/button_section.dart';
part 'widgets/sign_in_form.dart';
part 'widgets/top_component.dart';
part 'models/sign_in_carousel.dart';
part 'models/signin_model.dart';
part 'widgets/sign_up_form.dart';
part 'widgets/forgot_password.dart';
part 'widgets/terms_and_condition.dart';
